version: '2'

volumes:
  devpi_data:
    external: true

services:
  devpi:
    image: cloudhotspot/devpi
    volumes:
      - devpi_data:/var/lib/devpi
      - ./backup.bz2:/devpi-init.d/backup.bz2
    ports:
      - "8000:8000"
    stop_signal: SIGINT
    environment:
      DEVPI_USER: dev
      DEVPI_PASSWORD: ${DEVPI_PASSWORD}
      DEVPI_INDEX: root
      DEVPI_PORT: "8000"